### ISSUE TITLE
No donation link.

### ISSUE THREAD

**Issue by alaskalinuxuser** [Andrewerr/NextcloudServices#12]
Love this app and the work you put into it so far!
I don't have Gapps on my phone on purpose and use next cloud for personal storage and messaging, so this app is a big step in the right direction for notifications!

I looked on github and on fdroid, I can't find a donations link to properly thank you for this.
Updating fdroid would be great, or a link in the meantime would be good too.

**Comment by Andrewerr** [comment]
Thank you very much for appreciating my work! 
I have just added my liberapay to README and option to donate in the app and I think I would also add it to F-Droid, but this could take some time.

**Comment by alaskalinuxuser** [comment]
Thanks! Hit you up with a one time on librepay. Really appreciate your work!
