### ISSUE TITLE
Disable Account

### ISSUE THREAD

**Issue by sunjam** [Andrewerr/NextcloudServices#15]
I see a background connection notification even without enabling an account, and I'm wondering about the possibility of disabling an account via a toggle within settings .

This could be useful alongside #1 
Thanks for considering.

**Comment by Andrewerr** [comment]
Hello.
Yes I will implement such switch(for one account unless I'll implement  #1) in a next version

**Comment by Andrewerr** [comment]
Features to implement:
* [ ] Switch for enabling/disabling service

**Comment by Andrewerr** [comment]
Implemented in [v1.0-beta10](https://github.com/Andrewerr/NextcloudServices/releases/tag/v1.0-beta10), so closing the issue
