### ISSUE TITLE
Missing app icon

### ISSUE THREAD

**Issue by Donnnno** [Andrewerr/NextcloudServices#16]
Hi, I noticed that your app is missing an icon!

But instead of saying the obvious, I've created 3 variations for you to choose from: 

![nxtcld1](https://user-images.githubusercontent.com/31142286/130134576-f3268c7a-9e55-47ad-ae16-28825d2dc9ee.png)
![nxtcld2](https://user-images.githubusercontent.com/31142286/130134580-23c88426-f7e9-4c32-98cb-20c532872d1e.png)
![nxtcld3](https://user-images.githubusercontent.com/31142286/130134583-f5b6785d-19a3-4242-907d-221085dfacb9.png)

Let me know what you think about the suggestions ;)

**Comment by Andrewerr** [comment]
Hello
Thank you very much for creating an icons for my app :) I like the first icon the most :)

**Comment by Andrewerr** [comment]
So if I use your icon is there any license for it? And you prefer if I add your github page in Credits section(both on GitHub and app) or some other specific page?

**Comment by Donnnno** [comment]
Thanks! The icon is entirely free for you to use in any way you like! I'll provide you with an SVG & I also can make a pull request for the icon :^) 

You can credit me if you want to, just refer to my github page ;)

**Comment by Andrewerr** [comment]
Closing an issue as #18 just got merged
