### ISSUE TITLE
Improve "Credits" activity

### ISSUE THREAD

**Issue by Andrewerr** [Andrewerr/NextcloudServices#17]
Credits activity currently very simple and so do not have enough information as well as being inconvinient for user. So following changes should be introduced:
* [x] Add arrow for navigating back to SettingsActivity(just like SettingActivity have exit arrow)
* [x] Add description for each contributor/component(e.g. component, contribution, license, etc.)
* [ ] Separate lists for libraries and authors of commits/resource/etc.(won't implement since it is not user-friendly)

**Comment by Devansh-gaur-1611** [comment]
Hello, I want to contribute to this issue as a beginner but I am unable to find the credits activity. Can anyone please help me by telling me that where it is present

**Comment by Andrewerr** [comment]
Hello.
Sorry for this: I just forgot to rename it since it was initially designed for only putting licenses, but now I think there should be all people who contributed to this project. So I have just renamed it in last commit :) 
Now you can find it by path `app/src/main/java/com/polar/nextcloudservices/CreditsActivity.java`

**Comment by Devansh-gaur-1611** [comment]
Thanks for this info

**Comment by Devansh-gaur-1611** [comment]
Hello, I have opened the app using android studio. But I am getting an error "Cannot access com.polar.nextcloudservices.NextcloudAbstractAPI" And even after rebuilding it again and again the issue is not solving. Please help me. I have attached the screenshots for the same
![Screenshot (149)](https://user-images.githubusercontent.com/89275109/130331990-a323695e-0754-400f-b1b5-2f8c55fa5cce.png)
![Screenshot (148)](https://user-images.githubusercontent.com/89275109/130331991-45dfccbc-e648-4103-87cb-c6eee9ce0db6.png)
![Screenshot (147)](https://user-images.githubusercontent.com/89275109/130331992-f40df135-72aa-4d00-9788-e7af4936d9b1.png)

**Comment by Andrewerr** [comment]
Since build is succesful(as I can see from last screenshot) it seem to be problem with an Android Studio cache. So I guess doing gradle sync would help, but if it doesn't you can try to do what Stackoverflow is suggested:
* https://stackoverflow.com/questions/38420228/android-studio-cannot-access-the-function-in-the-other-class
* https://stackoverflow.com/questions/26422860/android-studio-library-error-package-does-not-exist/68736360#68736360

**Comment by Devansh-gaur-1611** [comment]
Hi, I have created a pull request after solving the first two issues of this issue #17. Please have a look over it. Also please write the last issue of issue #17 in detail please, actually I am unable to understand what to do in the 3rd issue.

**Comment by Andrewerr** [comment]
The third issue was mostly about that I have not imagined way to properly place license name for everyone(so what I've imagined is two lists(inside one activity or even having separate activities),but it is not user-friendly). In fact your implementation solves this problem, because we can use `\n` in strings, e.g. 
```XML
<item>Contribution: NumberPickerPreference\nLicense: LGPL-3.0</item>
``` 
This would place a "License:..." text under "Contribution:..." line for those people whose contribution has license.
So since everything is implemented I'm closing this issue. Thank you once more for your contribution!

**Comment by Devansh-gaur-1611** [comment]
Thanks for the compliment. This was my first contribution to open source, and I am glad that my work was helpful to you.
