### ISSUE TITLE
[Suggestion] Filter Notifications

### ISSUE THREAD

**Issue by newhinton** [Andrewerr/NextcloudServices#24]
This is a nice app that gets me notifications quickly, thanks!

However, it would be nice if it were possible to filter (and therefore not show) notifications per app.

As an example: I currently get the notifications from the calendar app twice, because my device-calendar-app also shows notifications. I think its beneficial to not get them twice

**Comment by Andrewerr** [comment]
Hello. You are welcome :)
I will implement notification filtering by app. By the way if you have got a device running Android 10+(or maybe 8+, honestly I do not remember when channels got introduced) you can use "About app > Notifications" and disable for example "Calendar" channel.
