### ISSUE TITLE
Tapping notification does not open Nextcloud app

### ISSUE THREAD

**Issue by myuseraccount** [Andrewerr/NextcloudServices#36]
I have my two-factor login configured with an option to use a Nextcloud app notification for logging in through a desktop browser.  I get the notification with Nextcloud Services, but tapping the notification from the drawer or the pop-up overlay seems to do nothing.  I would expect it to at least open Nextcloud on my phone, if not actually go to the notifications section of the app.

Manually navigating to notifications in the Nextcloud app shows the notification that corresponds to my push notification, but it would be great to not have to go to those extra steps to interact with the notification event.  In the case of using it for two-factor login, I already know to expect something on my phone app, so the pop-up notification doesn't serve any purpose if it isn't a quick way to go there.

My phone is running Android 11, with the stock Samsung ROM.  I haven't removed anything from Google Play Services, I just don't have a Google account on this phone and don't use the Play Store.

**Comment by Andrewerr** [comment]
Hello. Thanks for reporting this bug. Tapping a notification should open a web-browser in case if notification provides a URL to open. I will investigate the notification which is sent by two-factor authenitcation app on my own Nextcloud instance and try to improve a user experience.

**Comment by Andrewerr** [comment]
**Tasks:**
* [ ] Implement separate notificatio prcoessor to handle TOTP flow

**Comment by Andrewerr** [comment]
Tested on my own nextcloud instance with 2FA notification, no problems was found, so closing this issue
