### ISSUE TITLE
Reply feature does not work properly

### ISSUE THREAD

**Issue by Andrewerr** [Andrewerr/NextcloudServices#39]
I would like to share my own experience concerning this issue.
I also am on GrapheneOS (latest) and latest NextcloudServices (v1.0-beta12)

Notifications are working on my device, including talk/spreed. However, the "Reply" functionality in the Android notification, doesn't send message. @TheDarkula do you still have this issue ?

![Screenshot_20221121-113253](https://user-images.githubusercontent.com/21262052/203029251-561c2881-b1ce-466f-8813-409710a92ca4.png)

_Originally posted by @NablaMetal in https://github.com/Andrewerr/NextcloudServices/issues/38#issuecomment-1321846352_

**Comment by Andrewerr** [comment]
@NablaMetal Hello once again. Unfortunately my Nextcloud instance is currently down and I wouldn't be able to reproduce your issue, so can you please try grabbing any exceptions while responding with quick replies. Though probably the problem is that new notification APIs in S already dropped support of that APIs that I have used in this app, but it is still worth trying `grep`'ing some exceptions

**Comment by NablaMetal** [comment]
I'm not seeing anything suspicious in nextcloud logs, with level 0. Did you meant greping error on the server or the client (I mean the "nextcloud services" app) ?

**Comment by Andrewerr** [comment]
Yes, I mean grepping exceptions from client app as I do not really think that Nextcloud would change API for sending messages in talk on server side

**Comment by NablaMetal** [comment]
Sorry I don't know how to do that on Android, there's no log related option in the app and I'm no dev.

**Comment by Andrewerr** [comment]
Reply feature is fixed in 1.0-beta13 by @freeflyk
