### ISSUE TITLE
Preview for Images in Notifications

### ISSUE THREAD

**Issue by freeflyk** [Andrewerr/NextcloudServices#41]
Hi Andrewerr.

Thank you for your effort regarding NetxloudServices. I would like to contribute with an additional feature that I'm currently missing. If a talk messages send by a user contains an image I would like to see the preview of that image in the notification along with the option to reply to that message. I already started working on this feature and it works well so far using the SSO login method for nextcloud. You can find the current implementation in [my repo](https://github.com/freeflyk/NextcloudServices/tree/NotificationImagePreview). Let me know if you have any thoughts regarding this feature.
![GitHubMessageImagePreviewNotification](https://user-images.githubusercontent.com/65976525/212500049-f3a5c039-410e-43b4-93e4-3aed5abfdc26.png)

**Comment by Andrewerr** [comment]
Hello freeflyk. 
Thank you for developing this feature. I looked through your code and it seems ok to me. Please create a pull request from your repo, so I would review it more carefully and if everything is ok I would merge it to the main branch, so your feature would become available in next release

**Comment by freeflyk** [comment]
Hello Andrewerr.

I have created a pull request. Please note that I proposed some code for the HttpAPI file (username/password login). However, since the app cannot connect to my NC instance using the username/password login option I'm not able to test the code!  I hope that it will anyway be helpfull for you.

**Comment by Andrewerr** [comment]
Hello freeflyk.
Thank you for your contribution very much! No problem with testing HttpApi: I am able to test it on my instance :)

**Comment by Andrewerr** [comment]
Closing this issue as everything was merged and tested for both HTTP API and SSO API
