### ISSUE TITLE
open chats in custom tab rather than nextcloud talk

### ISSUE THREAD

**Issue by freeflyk** [Andrewerr/NextcloudServices#47]
Hello Andrewerr.

Since a click on a chat message notification will open nextcloud talk in the main activity rather than the specific chat the message was send from I would like to propose to open a custom browser window instead. The advantage over a common browser activity is that all the layout is reduced to a minimum, the URL cannot be altered and a closing button is presented to close the intent. If you like I can create a pull request for this feature from [my branch](https://github.com/freeflyk/NextcloudServices/tree/BrowserIntentChat). I also updated the credits and donate intents ...

![GitHubCustomTabsIntent](https://user-images.githubusercontent.com/65976525/215778921-9e9ed3fc-0852-421e-8aea-0c567f6eb0eb.png)

**Comment by Andrewerr** [comment]
Hello freeflyk.
Thankyou for improving intents. Please create pull request from your branch to main branch of this repo

**Comment by freeflyk** [comment]
Hello andrewerr.

Thanks for considering the pull request. I initially tried to open the nextcloud talk app with the correct chat opened. However, I was not able to open anything beside the main activity of talk. Also I think that this is not intended by the developers in the first place... Thus, I figure that it does not make sense to open talk when tapping on the notification since its not really an improvement over opening talk from the desktop directly. Instead, one could unify the notification response by simply always opening a browser that leads the user directly to the correct page.

**Comment by Andrewerr** [comment]
Closing issue as PR #48 is merged
