### ISSUE TITLE
URLs of action links are not cleaned up properly

### ISSUE THREAD

**Issue by freeflyk** [Andrewerr/NextcloudServices#49]
Hello Andrewerr.

In the `ActionsNotificationProcessor.java` you make use of the method `cleanUpURLIfNeeded(domain, target)` function which is supposed to cleanup the url to keep only the path and remove the protocol as well as the domain. Since I only use SSO login option I never inserted my domain in the settings. This will lead to the function trying to remove `cloud.example.com` from the target link. Also I make use of a specific port which is used in the link which will not be removed by the function. In consequence this will break notifications of apps such as 2fa notification.
To overcome these limitations I would like to propose to convert the target link into a URL to then extract the path. I will submit a pull request for this issue so you can check.

**Comment by Andrewerr** [comment]
Closed as PR #50 is merged
