### ISSUE TITLE
Update notification permissions for Android 13 compatibility

### ISSUE THREAD

**Issue by myuseraccount** [Andrewerr/NextcloudServices#51]
I've discovered that my phone (Pixel running Android 13) will not let me activate notifications for some apps, and NextcloudServices is one of them.  It has the notification permission for that app toggled off, greyed out, and a message on the screen with the toggle saying, "At your request, Android is blocking this app's notifications from appearing on this device".  I didn't make this choice, and no setting is able to deactivate the block.

My research has suggested that this is due to a new security model in Android 13.
[Google developer guide](https://developer.android.com/develop/ui/views/notifications/notification-permission)

**Comment by Andrewerr** [comment]
Hello and sorry for long response. I have already implemented notification request, but unsure if it works as my own ROM is still on LOS19.1(Android 12) base. If you would like to test whether it works before next release you may install development bleeding-edge version from Actions(latest one is https://github.com/Andrewerr/NextcloudServices/actions/runs/4136114311), though keep in mind that APK there is unsigned and so you need to install it via adb

**Comment by Rikj000** [comment]
Hi @Andrewerr,
I just tested the build you linked on Android 13 / LineageOS 20 and can confirm that it fixes this issue! :tada:

**Comment by Andrewerr** [comment]
Hello @Rikj000 
Thankyou for testing this fix. I would make a new release as soon as I will have time to move some non-working new features to another branch and write changelog for new version

**Comment by Andrewerr** [comment]
Closing issue as release including fix for this issue was just released
