### ISSUE TITLE
PayPal won't process my donation

### ISSUE THREAD

**Issue by DuncanLithgow** [Andrewerr/NextcloudServices#53]
PayPal says @Andrewerr is not accepting donations at this time.

**Comment by DuncanLithgow** [comment]
so this is odd, the payment seems to have been processed anyway.

**Comment by Andrewerr** [comment]
Hello. Thank you for donating me!
Sorry my paypal account is currently disabled, so I have received no money. If you have not received money back, please write to LiberaPay or PayPal support
