### ISSUE TITLE
The setting for request frequency is not updated

### ISSUE THREAD

**Issue by Andrewerr** [Andrewerr/NextcloudServices#58]
The request frequency is ignored and always fallback to default one regardless polling interval. This may contribute to increase energy usage due to requests(#56)

**Comment by xandris** [comment]
hi i installed 1.0-beta16 on June 23 and this one-second polling appears in my logs going back to July 30. changing my polling rate to 179 and back to 180 appears to have fixed it but if users don't have access to their server access logs they might not know why their battery is still draining

**Comment by xandris** [comment]
When I made my comment, I reset the frequency back to 180 seconds and the access log reflected that.

Yesterday, Nextcloud Services started polling with a 3 second interval again. I would not consider this bug fixed.

**Comment by Andrewerr** [comment]
Hello. Sorry for the long response. Thankyou for reporting about this behavior.
As per your first comment: the problem in synchronization between activity and preference storage led to missynchronization between value in activity and preference backend. Though I do not know method to synchronize activity and preference backend directly on update(I would need to forcibly open app on update to do this which is not very nice towards users, especially to those who enabled updates in background in F-Droid), so the fix for this bug works properly, but some users may have un-updated settings stored from previous version.
As per your second comment: it seems that it is completely new bug as settings seem to have changed themselves without action from users(i.e. yours) side, so I would open new issue for this

**Comment by xandris** [comment]
@Andrewerr thank you sorry for the confusion
