### ISSUE TITLE
Settings updated in storage without changes in MainActivity

### ISSUE THREAD

**Issue by Andrewerr** [Andrewerr/NextcloudServices#59]
> When I made my comment, I reset the frequency back to 180 seconds and the access log reflected that.
>
> Yesterday, Nextcloud Services started polling with a 3 second interval again. I would not consider this bug fixed.

_Originally posted by @xandris in https://github.com/Andrewerr/NextcloudServices/issues/58#issuecomment-1708792909_

**Comment by xandris** [comment]
It happened yesterday after I updated my phone's OS.

When it occurs, you can watch your server logs get polled for notifications every 3s—the actual polling interval—while in the NextcloudServices preferences pane you'll see the expected polling interval.

Turning polling off and back on doesn't set the actual to be the expected. The only remedy is to toggle the expected interval to some other value and then back to the desired value.

It isn't only triggered by phone updates, but that's the only concrete event I've found. Other times are mysterious, like "maybe during battery saver?" or "maybe during airplane mode?"

**Comment by Andrewerr** [comment]
Thankyou for the information! 
Those action restart service and it seems this changes settings at least inside of service itself.

**Comment by Andrewerr** [comment]
Hello.
It seems that issue hasn't occured since additional checks have been implemented(at least on my device). If you run in any problems like this, please try first re-logining in to app(clean app data and cache and then re-setup it), in case if it doesn't helps, please reopen this issue or (better) create a new one
