### ISSUE TITLE
idea: separate out calendar event notifications

### ISSUE THREAD

**Issue by meonkeys** [Andrewerr/NextcloudServices#60]
What do you think about separating out calendar event notifications? I get double notifications from all calendar events: one from NextcloudServices and one from the built-in Calendar app (sync events are sync'd to my phone). If they were separated out I would mute these kinds of notifications from NextcloudServices.

**Comment by Andrewerr** [comment]
Hello. Thank you for idea. I think it would be great to have a separate notification processor for calendar events, so it would be possible to receive optimized notifications from Nextcloud Calendar. 
By the way, why wouldn't you just disable calendar channel(app should create a channel for each app automatically)?

**Comment by meonkeys** [comment]
>  By the way, why wouldn't you just disable calendar channel(app should create a channel for each app automatically)?

For perhaps a silly reason: the notifications I get from the phone's Calendar app are more useful. They include the content of the event, and if there's a location specified it includes a link so I can open it in the Maps app with one touch.

**Comment by Andrewerr** [comment]
Oh, sorry, you probably misunderstood my question. NextcloudServices should have a calendar channel already as it creates a channel for each Nextcloud app it ever received notification. E.g. when it receives first calendar notification it should create a notification channel for calendar events. So you may disable this channel and get rid of NextcloudServices notifications without waiting me to implement calendar notifications :)

**Comment by meonkeys** [comment]
Ah, gotcha! Is the channel for event notifications called "Dav"?

![ns](https://github.com/Andrewerr/NextcloudServices/assets/50639/faf822d9-3803-4f1a-adb1-42168f537089)

I'll try turning off Dav...

**Comment by Andrewerr** [comment]
Not sure about the name as I have never received calendar notifications from Nextcloud. At least during debug of this app ;)
The name is generated automatically based on how Nextcloud itself names this app(unless the app requires creation of customized notification)

**Comment by meonkeys** [comment]
Looks like the calendar event notifications were under "Dav". Toggling that did what I was looking for. Thanks!
